---
- hosts: test
  remote_user: sis
  tasks: 
   - user: name=ansible uid=2000 shell=/bin/bash password=$6$lP.nmAElEW7$lel.7BLqwO.IqHpTZjZ1rfF5kkVzsdhAPOJ76mtzwcu72cprJ804pXUe/HUR01xKs9FYVWxFdZgwdoRMghh1i.
